"""empty message

Revision ID: 04a01ac0dda0
Revises: b05731dc75ac
Create Date: 2021-06-24 16:07:20.553893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04a01ac0dda0'
down_revision = 'b05731dc75ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolist', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolist', 'completed')
    # ### end Alembic commands ###
