"""empty message

Revision ID: 495312920f98
Revises: 
Create Date: 2021-06-15 08:11:10.041116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '495312920f98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
