"""empty message

Revision ID: e743aab1170a
Revises: 495312920f98
Create Date: 2021-06-15 08:25:21.524306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e743aab1170a'
down_revision = '495312920f98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todo SET completed = False WHERE completed IS NULL;')
    
    op.alter_column('todo', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
